---
- name: Set hostname
  command: /usr/local/openvpn_as/scripts/sacli --key host.name --value $EIP ConfigPut
- name: Set vpn.client.tls_version_min
  command: /usr/local/openvpn_as/scripts/sacli --key vpn.client.tls_version_min --value 1.2 ConfigPut
- name: Set vpn.client.tls_version_min_strict
  command: /usr/local/openvpn_as/scripts/sacli --key vpn.client.tls_version_min_strict --value true ConfigPut
- name: Set vpn.server.tls_version_min
  command: /usr/local/openvpn_as/scripts/sacli --key vpn.server.tls_version_min --value 1.2 ConfigPut
- name: Set cs.tls_version_min
  command: /usr/local/openvpn_as/scripts/sacli --key cs.tls_version_min --value 1.2 ConfigPut
  - name: Set cs.tls_version_min_strict
  command: /usr/local/openvpn_as/scripts/sacli --key cs.tls_version_min_strict --value true ConfigPut
- name: Set vpn.client.config_text
  command: /usr/local/openvpn_as/scripts/sacli --key vpn.client.config_text --value 'cipher AES-256-CBC' ConfigPut
- name: Set cs.openssl_ciphersuites
  command: /usr/local/openvpn_as/scripts/sacli --key cs.openssl_ciphersuites --value 'EECDH+CHACHA20:EECDH+AES256:!EECDH+AES128:!RSA:!3DES:!MD5:!RC4:!ECDHE-RSA-AES256-SHA:!ECDHE-RSA-AES256-SHA3' ConfigPut
