---
- name: YUM | Install EPEL Repo
  yum:
    lock_timeout: 180
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  tags: epel-repo
- name: YUM | Install Certbot
  yum:
    lock_timeout: 180
    name: '{{ packages }}'
    state: present
  vars:
    packages:
    - certbot
    - python2-certbot
    - python2-certbot-dns-route53
