---
- hosts: localhost
  gather_facts: true
  become: yes
  vars:
    aws_region: "eu-west-1"
  pre_tasks:
    - include_tasks: install-roles.yml
    - name: Install or update pip
      package:
        name: "python2-pip"
        state: present
    - name: PIP | install python library dependancys for amazon.aws collection
      pip:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
         - boto3
         - botocore<1.20.0,>=1.19.33
  tasks:
    - include_tasks: run-role.yml
