---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - openvpn
- include_tasks: install-openvpn.yml
- include_tasks: install-certbot.yml
#- include_tasks: config-certbot.yml
#- include_tasks: config-openvpn-core.yml
#- include_tasks: config-openvpn-ldap.yml