---
- name: Set default AWS region within boto3
  ini_file:
    path: ~/.aws/config
    section: default
    option: region
    value: "{{ aws_region }}"
    mode: 0655
    backup: yes
- name: Run openvpnas Role
  import_role:
    name: pcanham.openvpnas
  vars:
    enable_ldap_config: true
    enable_letencrypt_config: true
    admin_user: "{{ lookup('aws_ssm', 'openvpnas_admin_user') }}"
    admin_password: "{{ lookup('aws_ssm', 'openvpnas_admin_password') }}"
    certificate_email: "{{ lookup('aws_ssm', 'certificate_email') }}"
    openvpnas_dns: "{{ lookup('aws_ssm', 'openvpnas_dns') }}"
    ldap_realm: "{{ lookup('aws_ssm', 'openvpnas_ldap_realm') }}"
    ldap_server: "{{ lookup('aws_ssm', 'openvpnas_ldap_server') }}"
    ldap_bind_dn: "{{ lookup('aws_ssm', 'openvpnas_ldap_bind_dn') }}"
    ldap_bind_pw: "{{ lookup('aws_ssm', 'openvpnas_ldap_bind_pw') }}"
    ldap_base_dn: "{{ lookup('aws_ssm', 'openvpnas_ldap_base_dn') }}"
    ldap_add_req: "{{ lookup('aws_ssm', 'openvpnas_ldap_additional_params') }}"
